#
# Digital Voice Modem - Bridge
#
# @package DVM / Bridge
#

# Time in seconds between pings to peers.
pingTime: 5

# Flag indicating whether or not the router should debug display all packets received.
rawPacketTrace: false
# Audio gain for received audio frames.
audioGain: 3.0
# Audio transmit mode (1 - DMR, 2 - P25).
txMode: 2

#
voxSampleLevel: 30.0

#
# Logging Configuration
#   Logging Levels:
#     1 - Debug
#     2 - Message
#     3 - Informational
#     4 - Warning
#     5 - Error
#     6 - Fatal
#
log:
    # Console display logging level (used when in foreground).
    displayLevel: 1
    # File logging level.
    fileLevel: 1
    # Full path for the directory to store the log files.
    filePath: .
    # Log filename prefix.
    fileRoot: dvmbridge

# Textual Name
name: BRIDGE
# Network Peer ID
peerId: 9000123
# Hostname/IP address of FNE master to connect to.
address: 192.168.1.128
# Port number to connect to.
port: 62031
# FNE access password.
passphrase: Centrunk!

#
rxFrequency: 0
#
txFrequency: 0
#
latitude: 0.0
#
longitude: 0.0
#
location: Anywhere, USA

# Source "Radio ID" for transmitted audio frames
sourceId: 4000
# Talkgroup ID for transmitted/received audio frames
destinationId: 31611
# Slot for received/transmitted audio frames
slot: 1


# Enable local audio over speakers
localAudio: false
# Enable PCM audio over UDP
udpAudio: true
# PCM over UDP send port
udpSendPort: 34001
# PCM over UDP send address destination
udpSendAddress: "127.0.0.1"

#udpRecievePort: 32001
#udpRecieveAddress: 127.0.0.1